### PR TITLE
Add Set Vacation Mode functionality

### PR DESCRIPTION
**Pull request by FuzzyMistborn**
API: https://www.ecobee.com/home/developer/api/documentation/v1/functions/CreateVacation.shtml

Fixes https://github.com/nkgilley/python-ecobee-api/issues/42

(I'm still a bit of a python newb, but I tried to base this off existing functionality and just editing to fit the required calls)

### CODE REVIEW

**Comment by marthoc** [comment]
Can you also create a function to delete a vacation? See: https://www.ecobee.com/home/developer/api/documentation/v1/functions/DeleteVacation.shtml. That way I can add this functionality to Home Assistant as two companion services - one to create vacations and one to delete them.

**Comment by marthoc** [comment]
Nevermind - I see that the delete functionality already exists in the library.

My only suggestion is to rename the function to "create_vacation" as that is the name given to it by the ecobee API.

**Comment by FuzzyMistborn** [comment]
Yeah, the delete functionality has been there for a while it looks like.  Would love this to be in HomeAssistant so I can automate vacations based on my Google Calendar but the coding required for that is well beyond me.

**Comment by marthoc** [comment]
Should be fairly trivial to add once this is added to the base library. Once @nkgilley is happy with this, merges it, and cuts a new release, I'll open a PR to add services in Home Assistant.

**Comment by marthoc** [comment]
I just reviewed more closely and it looks like you are missing a few other optional args: fan (The fan mode during the vacation) and fanMinOnTime (The minimum number of minutes to run the fan each hour). Make those kwargs at the end of the current call signature and default them to "auto" and 0 (the defaults listed in the ecobee API). 

My 2c - also I think that vacation_name should not be a keyword arg but a positional arg (it should be mandatory and not optional) since the user will need to know that name in order to delete the vacation I don't think the library should be providing a default - in which case move it after index but before cool_temp.

**Comment by nkgilley** [comment]
Thanks!

**Pull request merged**
